version: '3'

services:
  # Servicio de la base de datos MySQL para WordPress
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: word
      MYSQL_PASSWORD: word
    ports:
      - 3308:3308
  # Servicio de WordPress
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: word
      WORDPRESS_DB_PASSWORD: word
volumes:
  db_data:
  wordpress_data:
